# Generated by Django 5.2.7 on 2025-11-30 12:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g., 'Bread', 'Scones', 'KDF')", max_length=100, unique=True)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Current selling price per packet/unit (KES)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='Optional product description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = archived, not available for new production')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('parent_product', models.ForeignKey(blank=True, help_text='Parent product for quality tiers (e.g., Bread Leftovers → Bread)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_products', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Recipe name (e.g., 'Bread Mix Standard')", max_length=100)),
                ('expected_yield', models.DecimalField(decimal_places=2, help_text='Expected packets/units produced per mix', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('is_fixed_yield', models.BooleanField(default=True, help_text='True = machine-weighed (exact), False = hand-cut (variable)')),
                ('yield_variance_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum expected yield (for variable yield products)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('yield_variance_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum expected yield (for variable yield products)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only ONE active mix per product')),
                ('notes', models.TextField(blank=True, help_text='Recipe notes, special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixes_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixes_updated', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Which product this recipe produces', on_delete=django.db.models.deletion.PROTECT, related_name='mixes', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Mixes',
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MixIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item_id', models.IntegerField(help_text='ID mapping to inventory item (1-23). See inventory routing.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)])),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text='Amount needed per mix in base units', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_of_measure', models.CharField(help_text='Base unit (kg, L, units) - must match inventory item', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Special instructions (e.g., 'sifted flour')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mix', models.ForeignKey(help_text='Which recipe this ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.mix')),
            ],
            options={
                'ordering': ['inventory_item_id'],
                'constraints': [models.UniqueConstraint(fields=('mix', 'inventory_item_id'), name='unique_ingredient_per_mix')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='products_pr_is_acti_69be20_idx'),
        ),
        migrations.AddConstraint(
            model_name='mix',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='unique_active_mix_per_product'),
        ),
    ]
