# Generated by Products App - Seed Migration

from django.db import migrations
from decimal import Decimal


def seed_products_and_mixes(apps, schema_editor):
    """
    Seed core products and their mixes with actual bakery recipes.
    
    Products:
    - Bread (main) + Bread Leftovers (sub)
    - Scones (main) + Scones Leftovers (sub)  
    - KDF (main) + KDF Leftovers (sub)
    
    Mixes include actual ingredient quantities from bakery operations.
    """
    Product = apps.get_model('products', 'Product')
    Mix = apps.get_model('products', 'Mix')
    MixIngredient = apps.get_model('products', 'MixIngredient')
    User = apps.get_model('accounts', 'User')
    
    # Get system user for audit fields
    system_user = User.objects.filter(is_superuser=True).first()
    if not system_user:
        system_user = User.objects.first()
    
    if not system_user:
        print("⚠️  No users found. Skipping product seeding.")
        return
    
    # ===== CREATE MAIN PRODUCTS =====
    bread, _ = Product.objects.get_or_create(
        name='Bread',
        defaults={
            'selling_price': Decimal('60.00'),
            'description': 'Main bread product - machine sliced, fixed yield',
            'created_by': system_user,
        }
    )
    
    scones, _ = Product.objects.get_or_create(
        name='Scones',
        defaults={
            'selling_price': Decimal('45.00'),
            'description': 'Main scones product - machine weighed, fixed yield',
            'created_by': system_user,
        }
    )
    
    kdf, _ = Product.objects.get_or_create(
        name='KDF',
        defaults={
            'selling_price': Decimal('35.00'),
            'description': 'KDF (Kenyan Doughnut Fritters) - hand-cut, variable yield',
            'created_by': system_user,
        }
    )
    
    # ===== CREATE SUB-PRODUCTS (LEFTOVERS) =====
    Product.objects.get_or_create(
        name='Bread Leftovers',
        defaults={
            'selling_price': Decimal('50.00'),
            'description': 'Day-old or lower quality bread',
            'parent_product': bread,
            'created_by': system_user,
        }
    )
    
    Product.objects.get_or_create(
        name='Scones Leftovers',
        defaults={
            'selling_price': Decimal('40.00'),
            'description': 'Day-old or lower quality scones',
            'parent_product': scones,
            'created_by': system_user,
        }
    )
    
    Product.objects.get_or_create(
        name='KDF Leftovers',
        defaults={
            'selling_price': Decimal('30.00'),
            'description': 'Day-old or lower quality KDF',
            'parent_product': kdf,
            'created_by': system_user,
        }
    )
    
    # ===== CREATE MIXES WITH INGREDIENTS =====
    
    # ----- BREAD MIX -----
    bread_mix, created = Mix.objects.get_or_create(
        product=bread,
        name='Bread Mix Standard',
        defaults={
            'expected_yield': Decimal('132'),
            'is_fixed_yield': True,
            'notes': 'Standard bread recipe - 132 packets per mix',
            'created_by': system_user,
        }
    )
    
    if created:
        bread_ingredients = [
            # (inventory_item_id, quantity, unit, notes)
            (1, Decimal('36.000'), 'kg', 'Flour Type 1 - main flour'),
            (3, Decimal('4.500'), 'kg', 'Sugar'),
            (4, Decimal('0.060'), 'kg', 'Bread Improver (60g)'),
            (5, Decimal('0.280'), 'kg', 'Salt (280g)'),
            (6, Decimal('0.070'), 'kg', 'Calcium (70g)'),
            (7, Decimal('0.200'), 'kg', 'Yeast (200g)'),
            (13, Decimal('2.800'), 'kg', 'Cooking Fat'),
        ]
        
        for item_id, qty, unit, notes in bread_ingredients:
            MixIngredient.objects.create(
                mix=bread_mix,
                inventory_item_id=item_id,
                quantity_required=qty,
                unit_of_measure=unit,
                notes=notes
            )
        print(f"✅ Created Bread Mix with {len(bread_ingredients)} ingredients")
    
    # ----- SCONES MIX -----
    scones_mix, created = Mix.objects.get_or_create(
        product=scones,
        name='Scones Mix Standard',
        defaults={
            'expected_yield': Decimal('102'),
            'is_fixed_yield': True,
            'notes': 'Standard scones recipe - 102 packets per mix',
            'created_by': system_user,
        }
    )
    
    if created:
        scones_ingredients = [
            (1, Decimal('26.000'), 'kg', 'Flour Type 1'),
            (3, Decimal('3.800'), 'kg', 'Sugar'),
            (4, Decimal('0.050'), 'kg', 'Bread Improver (50g)'),
            (5, Decimal('0.280'), 'kg', 'Salt (280g)'),
            (6, Decimal('0.050'), 'kg', 'Calcium (50g)'),
            (7, Decimal('0.190'), 'kg', 'Yeast (190g)'),
            (13, Decimal('2.300'), 'kg', 'Cooking Fat'),
        ]
        
        for item_id, qty, unit, notes in scones_ingredients:
            MixIngredient.objects.create(
                mix=scones_mix,
                inventory_item_id=item_id,
                quantity_required=qty,
                unit_of_measure=unit,
                notes=notes
            )
        print(f"✅ Created Scones Mix with {len(scones_ingredients)} ingredients")
    
    # ----- KDF MIX -----
    kdf_mix, created = Mix.objects.get_or_create(
        product=kdf,
        name='KDF Mix Standard',
        defaults={
            'expected_yield': Decimal('102'),
            'is_fixed_yield': False,  # Variable yield (hand-cut)
            'yield_variance_min': Decimal('97'),
            'yield_variance_max': Decimal('107'),
            'notes': 'Standard KDF recipe - 97-107 packets per mix (hand-cut, variable)',
            'created_by': system_user,
        }
    )
    
    if created:
        kdf_ingredients = [
            (1, Decimal('50.000'), 'kg', 'Flour Type 1'),
            (3, Decimal('2.500'), 'kg', 'Sugar'),
            (5, Decimal('0.300'), 'kg', 'Salt (300g)'),
            (6, Decimal('0.060'), 'kg', 'Calcium (60g)'),
            (7, Decimal('0.160'), 'kg', 'Yeast (160g)'),
            (13, Decimal('1.500'), 'kg', 'Cooking Fat'),
            (14, Decimal('7.500'), 'L', 'Cooking Oil - for frying'),
        ]
        
        for item_id, qty, unit, notes in kdf_ingredients:
            MixIngredient.objects.create(
                mix=kdf_mix,
                inventory_item_id=item_id,
                quantity_required=qty,
                unit_of_measure=unit,
                notes=notes
            )
        print(f"✅ Created KDF Mix with {len(kdf_ingredients)} ingredients")
    
    print("✅ Products and Mixes seeding complete!")


def reverse_seed(apps, schema_editor):
    """Reverse seeding - for rollback"""
    Product = apps.get_model('products', 'Product')
    Mix = apps.get_model('products', 'Mix')
    
    # Delete mixes first (ingredients will cascade)
    Mix.objects.filter(
        name__in=['Bread Mix Standard', 'Scones Mix Standard', 'KDF Mix Standard']
    ).delete()
    
    # Delete products (sub-products must be deleted before parents)
    Product.objects.filter(
        name__in=['Bread Leftovers', 'Scones Leftovers', 'KDF Leftovers']
    ).delete()
    
    Product.objects.filter(
        name__in=['Bread', 'Scones', 'KDF']
    ).delete()
    
    print("✅ Products and Mixes seed data reversed")


class Migration(migrations.Migration):
    
    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]
    
    operations = [
        migrations.RunPython(seed_products_and_mixes, reverse_seed),
    ]
