# Generated by Django 5.2.7 on 2025-10-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Linked inventory item for cost tracking', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
    ]
