# Generated by Products App - Family Bread 800g Seed Migration

from django.db import migrations
from decimal import Decimal


def seed_family_bread(apps, schema_editor):
    """
    Seed Family Bread 800g product and its mix.
    
    Product: Family Bread 800g (main product)
    Mix: Variable yield (bounds TBD - using 100 as placeholder)
    
    Ingredients:
    - Flour Type 1: 40kg
    - Sugar: 5kg
    - Salt: 0.45kg
    - Yeast: 0.23kg (230g) - adjusted from 0.0023kg
    - Cooking Fat: 3kg
    - Bread Improver: 0.1kg (100g)
    - Calcium: 0.07kg (70g)
    """
    Product = apps.get_model('products', 'Product')
    Mix = apps.get_model('products', 'Mix')
    MixIngredient = apps.get_model('products', 'MixIngredient')
    User = apps.get_model('accounts', 'User')
    
    # Get system user for audit fields
    system_user = User.objects.filter(is_superuser=True).first()
    if not system_user:
        system_user = User.objects.first()
    
    if not system_user:
        print("⚠️  No users found. Skipping Family Bread seeding.")
        return
    
    # ===== CREATE FAMILY BREAD PRODUCT =====
    family_bread, created = Product.objects.get_or_create(
        name='Family Bread 800g',
        defaults={
            'selling_price': Decimal('80.00'),  # Placeholder price - adjust as needed
            'description': 'Family-size bread loaf 800g - variable yield',
            'created_by': system_user,
        }
    )
    
    if created:
        print(f"✅ Created product: Family Bread 800g")
    else:
        print(f"ℹ️  Product Family Bread 800g already exists")
    
    # ===== CREATE FAMILY BREAD MIX =====
    family_bread_mix, mix_created = Mix.objects.get_or_create(
        product=family_bread,
        name='Family Bread 800g Mix Standard',
        defaults={
            'expected_yield': Decimal('100'),  # Placeholder - adjust when bounds determined
            'is_fixed_yield': False,  # Variable yield (bounds TBD)
            'yield_variance_min': None,  # TBD - set when determined
            'yield_variance_max': None,  # TBD - set when determined
            'notes': 'Family Bread 800g recipe - variable yield (bounds to be determined)',
            'created_by': system_user,
        }
    )
    
    if mix_created:
        # Ingredients based on provided data
        # inventory_item_id mapping:
        # 1 = Flour Type 1, 3 = Sugar, 4 = Bread Improver, 5 = Salt,
        # 6 = Calcium, 7 = Yeast, 13 = Cooking Fat
        family_bread_ingredients = [
            # (inventory_item_id, quantity, unit, notes)
            (1, Decimal('40.000'), 'kg', 'Flour Type 1 - main flour'),
            (3, Decimal('5.000'), 'kg', 'Sugar'),
            (5, Decimal('0.450'), 'kg', 'Salt (450g)'),
            (7, Decimal('0.230'), 'kg', 'Yeast (230g)'),  # Adjusted from 0.0023kg
            (13, Decimal('3.000'), 'kg', 'Cooking Fat'),
            (4, Decimal('0.100'), 'kg', 'Bread Improver (100g)'),
            (6, Decimal('0.070'), 'kg', 'Calcium (70g)'),
        ]
        
        for item_id, qty, unit, notes in family_bread_ingredients:
            MixIngredient.objects.create(
                mix=family_bread_mix,
                inventory_item_id=item_id,
                quantity_required=qty,
                unit_of_measure=unit,
                notes=notes
            )
        print(f"✅ Created Family Bread 800g Mix with {len(family_bread_ingredients)} ingredients")
    else:
        print(f"ℹ️  Family Bread 800g Mix already exists")
    
    print("✅ Family Bread 800g seeding complete!")


def reverse_seed(apps, schema_editor):
    """Reverse seeding - for rollback"""
    Product = apps.get_model('products', 'Product')
    Mix = apps.get_model('products', 'Mix')
    
    # Delete mix first (ingredients will cascade)
    Mix.objects.filter(name='Family Bread 800g Mix Standard').delete()
    
    # Delete product
    Product.objects.filter(name='Family Bread 800g').delete()
    
    print("✅ Family Bread 800g seed data reversed")


class Migration(migrations.Migration):
    
    dependencies = [
        ('products', '0002_seed_products_and_mixes'),
        ('accounts', '0001_initial'),
    ]
    
    operations = [
        migrations.RunPython(seed_family_bread, reverse_seed),
    ]
