# Generated by Django 5.2.7 on 2025-11-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ingredient_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_stock',
            field=models.IntegerField(default=0, help_text='Current available stock in units'),
        ),
    ]
