# Generated by Django 4.2.23 on 2025-11-30 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_seed_products_and_mixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(db_index=True, help_text='Format: PRD-YYYYMMDD-XXX (e.g., PRD-20251129-001)', max_length=30, unique=True)),
                ('mix_snapshot', models.JSONField(help_text='\n        Complete mix data frozen at batch creation time.\n        Structure:\n        {\n            "mix_id": 1,\n            "mix_name": "Bread Mix 1",\n            "expected_yield": 132,\n            "ingredients": [\n                {\n                    "inventory_item_id": 1,\n                    "item_name": "Bakers Flour",\n                    "quantity_required": "36.000",\n                    "unit": "kg",\n                    "unit_price_at_batch": "85.50",\n                    "line_cost": "3078.00"\n                },\n                ...\n            ],\n            "total_mix_cost": "12500.00"\n        }\n        ')),
                ('quantity_produced', models.PositiveIntegerField(help_text='Actual units produced (e.g., 132 loaves)')),
                ('expected_yield', models.PositiveIntegerField(help_text='Expected yield from mix (snapshot from mix at batch time)')),
                ('total_ingredient_cost', models.DecimalField(decimal_places=2, help_text='Sum of all ingredient costs at batch time', max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, help_text='total_ingredient_cost / quantity_produced', max_digits=10)),
                ('production_date', models.DateField(db_index=True, help_text='Date of production')),
                ('production_time', models.TimeField(blank=True, help_text='Approximate time batch was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional production notes (quality observations, issues, etc.)')),
                ('mix', models.ForeignKey(help_text='Reference to the mix used (recipe frozen in mix_snapshot)', on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='products.mix')),
                ('produced_by', models.ForeignKey(help_text='User who recorded this batch', on_delete=django.db.models.deletion.PROTECT, related_name='produced_batches', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product being produced', on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Production Batch',
                'verbose_name_plural': 'Production Batches',
                'db_table': 'production_batches',
                'ordering': ['-production_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current available units for dispatch')),
                ('last_production_date', models.DateField(blank=True, help_text='Date of most recent production batch', null=True)),
                ('last_production_batch', models.ForeignKey(blank=True, help_text='Reference to most recent batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.productionbatch')),
                ('product', models.OneToOneField(help_text='The product this stock record tracks', on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Product Stocks',
                'db_table': 'product_stock',
            },
        ),
        migrations.CreateModel(
            name='BatchIngredientDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item_id', models.PositiveIntegerField(db_index=True, help_text='ID of the inventory item (1-15 for ingredients)')),
                ('item_name', models.CharField(help_text='Ingredient name at time of deduction (denormalized for audit)', max_length=100)),
                ('quantity_deducted', models.DecimalField(decimal_places=3, help_text='Amount deducted from inventory', max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement (kg, L, pieces, etc.)', max_length=20)),
                ('unit_price_at_deduction', models.DecimalField(decimal_places=2, help_text='last_purchase_unit_price from inventory at batch time', max_digits=10)),
                ('line_cost', models.DecimalField(decimal_places=2, help_text='quantity_deducted × unit_price_at_deduction', max_digits=12)),
                ('stock_before', models.DecimalField(decimal_places=3, help_text='Inventory stock level before this deduction', max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=3, help_text='Inventory stock level after this deduction', max_digits=12)),
                ('batch', models.ForeignKey(help_text='The production batch this deduction belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_deductions', to='production.productionbatch')),
            ],
            options={
                'verbose_name': 'Batch Ingredient Deduction',
                'verbose_name_plural': 'Batch Ingredient Deductions',
                'db_table': 'batch_ingredient_deductions',
                'ordering': ['batch', 'inventory_item_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PRODUCTION', 'Production (batch added)'), ('DISPATCH', 'Dispatch (sent to sales)'), ('RETURN', 'Return (unsold from dispatch)'), ('ADJUSTMENT', 'Manual adjustment')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('stock_before', models.PositiveIntegerField(help_text='Stock level before this movement')),
                ('stock_after', models.PositiveIntegerField(help_text='Stock level after this movement')),
                ('reference_type', models.CharField(help_text="Type of source record (e.g., 'ProductionBatch', 'SalesDispatch')", max_length=50)),
                ('reference_id', models.PositiveIntegerField(help_text='ID of the source record')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this movement')),
                ('product', models.ForeignKey(help_text='The product this movement affects', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Stock Movement',
                'verbose_name_plural': 'Product Stock Movements',
                'db_table': 'product_stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='product_sto_product_0460d4_idx'), models.Index(fields=['movement_type', 'created_at'], name='product_sto_movemen_91d7ab_idx'), models.Index(fields=['reference_type', 'reference_id'], name='product_sto_referen_5c4f71_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['production_date', 'product'], name='production__product_1f8ade_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['batch_number'], name='production__batch_n_e3235b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchingredientdeduction',
            index=models.Index(fields=['batch', 'inventory_item_id'], name='batch_ingre_batch_i_2e57ab_idx'),
        ),
        migrations.AddIndex(
            model_name='batchingredientdeduction',
            index=models.Index(fields=['inventory_item_id', 'created_at'], name='batch_ingre_invento_71f29d_idx'),
        ),
    ]
