# Generated by Django 5.2.7 on 2025-10-27 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_ingredient_inventory_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Production date', unique=True)),
                ('is_closed', models.BooleanField(default=False, help_text='🤖 AUTO: Set to True at 9PM by cron job')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when books were closed', null=True)),
                ('opening_bread_stock', models.IntegerField(default=0, help_text="🤖 AUTO: From previous day's closing_bread_stock")),
                ('opening_kdf_stock', models.IntegerField(default=0, help_text="🤖 AUTO: From previous day's closing_kdf_stock")),
                ('opening_scones_stock', models.IntegerField(default=0, help_text="🤖 AUTO: From previous day's closing_scones_stock")),
                ('bread_produced', models.IntegerField(default=0, help_text='🤖 AUTO: Sum of Bread batches')),
                ('kdf_produced', models.IntegerField(default=0, help_text='🤖 AUTO: Sum of KDF batches')),
                ('scones_produced', models.IntegerField(default=0, help_text='🤖 AUTO: Sum of Scones batches')),
                ('bread_dispatched', models.IntegerField(default=0, help_text='✏️ MANUAL: From dispatch records (Sales app)')),
                ('kdf_dispatched', models.IntegerField(default=0, help_text='✏️ MANUAL: From dispatch records')),
                ('scones_dispatched', models.IntegerField(default=0, help_text='✏️ MANUAL: From dispatch records')),
                ('bread_returned', models.IntegerField(default=0, help_text='✏️ MANUAL: From sales returns (Sales app)')),
                ('kdf_returned', models.IntegerField(default=0, help_text='✏️ MANUAL: From sales returns')),
                ('scones_returned', models.IntegerField(default=0, help_text='✏️ MANUAL: From sales returns')),
                ('closing_bread_stock', models.IntegerField(default=0, help_text='🤖 AUTO: Opening + Produced - Dispatched + Returned')),
                ('closing_kdf_stock', models.IntegerField(default=0, help_text='🤖 AUTO: Opening + Produced - Dispatched + Returned')),
                ('closing_scones_stock', models.IntegerField(default=0, help_text='🤖 AUTO: Opening + Produced - Dispatched + Returned')),
                ('diesel_cost', models.DecimalField(decimal_places=2, default=0, help_text='✏️ MANUAL: Daily diesel consumption (KES)', max_digits=10)),
                ('firewood_cost', models.DecimalField(decimal_places=2, default=0, help_text='✏️ MANUAL: Daily firewood cost (KES)', max_digits=10)),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, help_text='✏️ MANUAL: Daily electricity (estimated, KES)', max_digits=10)),
                ('fuel_distribution_cost', models.DecimalField(decimal_places=2, default=0, help_text='✏️ MANUAL: Fuel for trucks/Bolero (KES)', max_digits=10)),
                ('other_indirect_costs', models.DecimalField(decimal_places=2, default=0, help_text='✏️ MANUAL: Miscellaneous costs (KES)', max_digits=10)),
                ('total_indirect_costs', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: Sum of all indirect costs', max_digits=10)),
                ('reconciliation_notes', models.TextField(blank=True, help_text='Notes on stock reconciliation, variances, issues')),
                ('has_variance', models.BooleanField(default=False, help_text='🤖 AUTO: True if variance > 5% detected')),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: Variance % if detected', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_production_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_production_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Production',
                'verbose_name_plural': 'Daily Productions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IndirectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('DIESEL', 'Diesel (Production)'), ('FIREWOOD', 'Firewood'), ('ELECTRICITY', 'Electricity'), ('FUEL_DISTRIBUTION', 'Fuel (Distribution)'), ('OTHER', 'Other')], help_text='Type of indirect cost', max_length=20)),
                ('description', models.CharField(help_text="Description of cost (e.g., '20L diesel from Ikapolok')", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost amount in KES', max_digits=10)),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt/invoice number', max_length=100)),
                ('vendor', models.CharField(blank=True, help_text='Vendor/supplier name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirect_cost_details', to='production.dailyproduction')),
            ],
            options={
                'verbose_name': 'Indirect Cost Detail',
                'verbose_name_plural': 'Indirect Cost Details',
                'ordering': ['daily_production__date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(help_text='✏️ MANUAL: Batch number for the day (1, 2, 3...)')),
                ('start_time', models.TimeField(blank=True, help_text='✏️ MANUAL: When production started', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='✏️ MANUAL: When production finished', null=True)),
                ('actual_packets', models.IntegerField(help_text='✏️ MANUAL: Actual units/packets produced')),
                ('expected_packets', models.IntegerField(default=0, help_text='🤖 AUTO: From Mix.expected_packets')),
                ('variance_packets', models.IntegerField(default=0, help_text='🤖 AUTO: Actual - Expected')),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: (Variance / Expected) × 100', max_digits=5)),
                ('rejects_produced', models.IntegerField(default=0, help_text='✏️ MANUAL: Bread rejects (if applicable)')),
                ('ingredient_cost', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: From Mix.total_cost', max_digits=12)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: actual_packets × KES 3.3', max_digits=10)),
                ('allocated_indirect_cost', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: Proportional share of daily indirect costs', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: Ingredient + Packaging + Indirect', max_digits=12)),
                ('cost_per_packet', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: total_cost / actual_packets', max_digits=10)),
                ('selling_price_per_packet', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: From Product.price_per_packet', max_digits=10)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: actual_packets × selling_price_per_packet', max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: expected_revenue - total_cost', max_digits=12)),
                ('gross_margin_percentage', models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: (gross_profit / expected_revenue) × 100', max_digits=5)),
                ('quality_notes', models.TextField(blank=True, help_text='✏️ MANUAL: Notes on quality, issues, observations')),
                ('is_finalized', models.BooleanField(default=False, help_text='Locked after book closing (9PM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches_created', to=settings.AUTH_USER_MODEL)),
                ('daily_production', models.ForeignKey(help_text='Parent daily production record', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.dailyproduction')),
                ('mix', models.ForeignKey(help_text='✏️ MANUAL: Select mix (Bread Mix 1, KDF Mix 1, etc.)', on_delete=django.db.models.deletion.PROTECT, to='products.mix')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Batch',
                'verbose_name_plural': 'Production Batches',
                'ordering': ['daily_production__date', 'batch_number'],
                'unique_together': {('daily_production', 'batch_number')},
            },
        ),
    ]
