# Generated by Django 5.2.7 on 2025-12-21 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_seed_family_bread_stock'),
        ('products', '0003_seed_family_bread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PRODUCTION', 'Production (batch added)'), ('DISPATCH', 'Dispatch (sent to sales)'), ('RETURN', 'Return (unsold from dispatch)'), ('ADJUSTMENT', 'Manual adjustment'), ('WASTE', 'Waste disposal')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_number', models.CharField(db_index=True, help_text='Format: WST-YYYYMMDD-XXX', max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units disposed')),
                ('unit_value', models.DecimalField(decimal_places=2, help_text='Product selling price at disposal time', max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='quantity × unit_value (P&L expense)', max_digits=12)),
                ('source', models.CharField(choices=[('SALES_RETURN', 'Stale Leftovers'), ('BAKERY_STOCK', 'Expired in Bakery')], db_index=True, help_text='Where the waste originated', max_length=20)),
                ('reason', models.CharField(help_text='Reason for disposal (e.g., Stale, Mold, Damaged)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('disposal_date', models.DateField(db_index=True, help_text='Date when waste was disposed')),
                ('disposed_by', models.ForeignKey(help_text='User who recorded the disposal', on_delete=django.db.models.deletion.PROTECT, related_name='waste_disposed', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product that was disposed', on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='products.product')),
            ],
            options={
                'verbose_name': 'Waste Log',
                'verbose_name_plural': 'Waste Logs',
                'db_table': 'waste_log',
                'ordering': ['-disposal_date', '-created_at'],
                'indexes': [models.Index(fields=['disposal_date', 'product'], name='waste_log_disposa_7406d7_idx'), models.Index(fields=['source', 'disposal_date'], name='waste_log_source_317878_idx')],
            },
        ),
    ]
