# Generated by Django 5.2.7 on 2025-11-12 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Salesperson/Depot/School name', max_length=200, unique=True)),
                ('salesperson_type', models.CharField(choices=[('PERSON', 'Individual Salesperson'), ('DEPOT', 'Depot'), ('SCHOOL', 'School'), ('OTHER', 'Other')], default='PERSON', help_text='Type of sales entity', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salespeople_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salespeople_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salesperson',
                'verbose_name_plural': 'Salespeople',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(editable=False, help_text='Auto-generated: DSP-YYYYMMDD-NAME-001', max_length=50, unique=True)),
                ('dispatch_date', models.DateField(help_text='Date of dispatch')),
                ('bread_qty', models.PositiveIntegerField(default=0, help_text='Loaves of bread dispatched')),
                ('kdf_qty', models.PositiveIntegerField(default=0, help_text='KDF packets dispatched')),
                ('scones_qty', models.PositiveIntegerField(default=0, help_text='Scones packets dispatched')),
                ('crates_dispatched', models.PositiveIntegerField(default=0, help_text='Number of crates dispatched')),
                ('bread_sold', models.PositiveIntegerField(blank=True, help_text='Bread loaves sold', null=True)),
                ('bread_returned', models.PositiveIntegerField(blank=True, help_text='Bread loaves returned unsold', null=True)),
                ('kdf_sold', models.PositiveIntegerField(blank=True, help_text='KDF packets sold', null=True)),
                ('kdf_returned', models.PositiveIntegerField(blank=True, help_text='KDF packets returned unsold', null=True)),
                ('scones_sold', models.PositiveIntegerField(blank=True, help_text='Scones packets sold', null=True)),
                ('scones_returned', models.PositiveIntegerField(blank=True, help_text='Scones packets returned unsold', null=True)),
                ('bread_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue from bread sales (KES)', max_digits=10, null=True)),
                ('kdf_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue from KDF sales (KES)', max_digits=10, null=True)),
                ('scones_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue from scones sales (KES)', max_digits=10, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total revenue (KES)', max_digits=10, null=True)),
                ('crates_returned', models.PositiveIntegerField(blank=True, help_text='Number of crates returned', null=True)),
                ('crate_deficit', models.IntegerField(blank=True, help_text='Crate deficit (dispatched - returned)', null=True)),
                ('is_returned', models.BooleanField(default=False, help_text='Locks entire record after return')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dispatches', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_dispatches', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_dispatches', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.salesperson')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesperson',
            index=models.Index(fields=['name'], name='sales_sales_name_d574be_idx'),
        ),
        migrations.AddIndex(
            model_name='salesperson',
            index=models.Index(fields=['is_active'], name='sales_sales_is_acti_9bd5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['dispatch_number'], name='sales_dispa_dispatc_cc2eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['dispatch_date'], name='sales_dispa_dispatc_7a6ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['salesperson', 'dispatch_date'], name='sales_dispa_salespe_001fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['is_returned'], name='sales_dispa_is_retu_c57d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['deleted_at'], name='sales_dispa_deleted_1d4ef1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dispatch',
            unique_together={('salesperson', 'dispatch_date')},
        ),
    ]
