# Generated by Django 4.2.23 on 2025-11-04 17:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_unit_commission', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Commission earned per unit sold (KES)', max_digits=10)),
                ('bonus_threshold', models.DecimalField(decimal_places=2, default=Decimal('35000.00'), help_text='Revenue threshold for bonus commission (KES)', max_digits=10)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Bonus percentage above threshold (e.g., 7 for 7%)', max_digits=5)),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date when these settings become effective')),
                ('is_active', models.BooleanField(default=True, help_text='Only one settings record can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this configuration')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Settings',
                'verbose_name_plural': 'Commission Settings',
                'ordering': ['-effective_from'],
            },
        ),
    ]
