# Generated by Django 5.2.7 on 2025-12-01 15:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_products_and_mixes'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # STEP 1: Remove FK constraints from old models first
        migrations.RemoveField(
            model_name='salesperson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='updated_by',
        ),
        
        # STEP 2: Delete old models FIRST (before creating new ones)
        migrations.DeleteModel(
            name='Dispatch',
        ),
        migrations.DeleteModel(
            name='Salesperson',
        ),
        
        # STEP 3: Create new models
        migrations.CreateModel(
            name='SalesDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('dispatch_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('RETURNED', 'Returned')], db_index=True, default='DISPATCHED', max_length=20)),
                ('crates_dispatched', models.PositiveIntegerField(default=0)),
                ('is_returned', models.BooleanField(db_index=True, default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches_created', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(help_text='User with role=SALESMAN', limit_choices_to={'role': 'SALESMAN'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_dispatch',
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of dispatch', max_digits=10)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesdispatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='products.product')),
            ],
            options={
                'db_table': 'sales_dispatch_item',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(db_index=True)),
                ('total_units_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: sum(qty_sold × unit_price)', max_digits=12)),
                ('crates_returned', models.PositiveIntegerField(default=0)),
                ('crates_lost', models.PositiveIntegerField(default=0)),
                ('crates_damaged', models.PositiveIntegerField(default=0)),
                ('crates_marked_lost', models.BooleanField(default=False, help_text='True when lost crates issue is resolved')),
                ('crates_marked_damaged', models.BooleanField(default=False, help_text='True when damaged crates issue is resolved')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered by Accountant. NULL if commission disabled.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return', to='sales.salesdispatch')),
            ],
            options={
                'db_table': 'sales_return',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_dispatched', models.PositiveIntegerField(help_text='Quantity originally dispatched')),
                ('qty_sold', models.PositiveIntegerField()),
                ('qty_returned', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price from dispatch', max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, help_text='Auto-calculated: qty_sold × unit_price', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='products.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn')),
            ],
            options={
                'db_table': 'sales_return_item',
                'ordering': ['product__name'],
            },
        ),
        
        # STEP 4: Add indexes
        migrations.AddIndex(
            model_name='salesdispatch',
            index=models.Index(fields=['dispatch_number'], name='sales_dispa_dispatc_cc2eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatch',
            index=models.Index(fields=['dispatch_date'], name='sales_dispa_dispatc_7a6ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatch',
            index=models.Index(fields=['status'], name='sales_dispa_status_1fe070_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatch',
            index=models.Index(fields=['is_returned'], name='sales_dispa_is_retu_c57d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatch',
            index=models.Index(fields=['salesperson', 'dispatch_date'], name='sales_dispa_salespe_001fd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesdispatch',
            unique_together={('salesperson', 'dispatch_date')},
        ),
        migrations.AlterUniqueTogether(
            name='salesdispatchitem',
            unique_together={('dispatch', 'product')},
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_date'], name='sales_retur_return__9201ce_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['crates_marked_lost'], name='sales_retur_crates__b31938_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['crates_marked_damaged'], name='sales_retur_crates__c7563a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreturnitem',
            unique_together={('sales_return', 'product')},
        ),
    ]
