# Generated by Django 4.2.23 on 2025-11-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_commissionsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_number', models.CharField(help_text="Crate identifier (e.g., 'Crate A', 'Box 1')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(help_text='Parent dispatch', on_delete=django.db.models.deletion.CASCADE, related_name='crates', to='sales.dispatch')),
            ],
            options={
                'verbose_name': 'Dispatch Crate',
                'verbose_name_plural': 'Dispatch Crates',
                'ordering': ['crate_number'],
                'unique_together': {('dispatch', 'crate_number')},
            },
        ),
        migrations.CreateModel(
            name='CrateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_crate', models.IntegerField(help_text='Units of this product in this specific crate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch_crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crate_items', to='sales.dispatchcrate')),
                ('dispatch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crate_allocations', to='sales.dispatchitem')),
            ],
            options={
                'verbose_name': 'Crate Item',
                'verbose_name_plural': 'Crate Items',
                'unique_together': {('dispatch_crate', 'dispatch_item')},
            },
        ),
    ]
