# Generated by Django 5.2.7 on 2026-01-31 04:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rebuild_sales_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitem',
            name='line_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount given for this product line (e.g., 360 for bulk customer deals)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='revenue',
            field=models.DecimalField(decimal_places=2, help_text='Auto-calculated: (qty_sold × unit_price) - line_discount', max_digits=12),
        ),
    ]
