# Generated by Django 4.2.23 on 2025-11-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_dispatch_deleted_at_dispatch_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='crates_deficit',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='deficit_alert_sent',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='deficit_reason',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='deficit_resolved',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='revenue_deficit',
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sales_reconciled',
            field=models.BooleanField(default=False, help_text='True when sales reconciliation is complete'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='crate_condition',
            field=models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='good', help_text='Condition of returned crates', max_length=20),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='crates_returned',
            field=models.IntegerField(default=0, help_text='✏️ MANUAL: Number of crates returned for this product'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='bonus_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: Bonus above threshold (optional)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='cash_returned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='✏️ MANUAL: Cash collected from customers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='crates_returned',
            field=models.BooleanField(default=False, help_text='True when crate return is recorded'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='per_unit_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: Calculated from sales items (optional)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='🤖 AUTO: per_unit + bonus (optional)', max_digits=10),
        ),
    ]
