# Generated by Django 5.2.7 on 2025-10-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='expires_at',
            field=models.DateTimeField(help_text='Invitation expiry (default: 7 days from creation)'),
        ),
    ]
