# Generated by Django 5.2.7 on 2025-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userinvitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
