# Generated by Django 5.2.7 on 2025-10-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userinvitation_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'CEO / Developer'), ('ADMIN', 'Accountant'), ('PRODUCT_MANAGER', 'Production Manager'), ('DEPT_HEAD', 'Department Head'), ('DISPATCH', 'Dispatch Officer'), ('SALESMAN', 'Sales Representative'), ('SECURITY', 'Gate Man / Security'), ('BASIC_USER', 'Basic User (Self-Registered)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'CEO / Developer'), ('ADMIN', 'Accountant'), ('PRODUCT_MANAGER', 'Production Manager'), ('DEPT_HEAD', 'Department Head'), ('DISPATCH', 'Dispatch Officer'), ('SALESMAN', 'Sales Representative'), ('SECURITY', 'Gate Man / Security'), ('BASIC_USER', 'Basic User (Self-Registered)')], max_length=20),
        ),
    ]
