# Generated by Django 5.2.7 on 2025-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_alter_userinvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_primary_superadmin',
            field=models.BooleanField(default=False, help_text='Reserved for the first/primary SUPERADMIN (CEO/System Owner). Cannot be modified by other admins.'),
        ),
    ]
