# Generated by Django 5.2.7 on 2025-10-16 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('template_path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communications_message_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('cc', models.JSONField(blank=True, null=True)),
                ('bcc', models.JSONField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.CharField(db_index=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('context_data', models.JSONField(blank=True, null=True)),
                ('provider', models.CharField(default='gmail', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_email_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='communicati_recipie_5faa54_idx'), models.Index(fields=['template', 'sent_at'], name='communicati_templat_34af59_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('template', models.CharField(db_index=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('UNDELIVERED', 'Undelivered')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_sms_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['phone_number', 'status'], name='communicati_phone_n_4acbb4_idx')],
            },
        ),
    ]
