# Generated by Django 4.2.23 on 2025-11-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cratestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cratemovement',
            name='movement_type',
            field=models.CharField(choices=[('DISPATCH_OUT', 'Dispatched to Salesperson'), ('RETURN_IN', 'Returned from Salesperson'), ('PURCHASE', 'New Crates Purchased'), ('DAMAGE', 'Crates Damaged'), ('REPAIR', 'Crates Repaired'), ('COUNT', 'Physical Count Adjustment')], help_text='Type of crate movement', max_length=20),
        ),
    ]
