# Generated by Django 4.2.23 on 2025-12-06 04:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_products_and_mixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('REPORT', 'Report Email'), ('ALERT', 'Alert Email')], default='REPORT', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportInventorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item_id', models.PositiveIntegerField(help_text='Reference to inventory item (1-23)')),
                ('item_name', models.CharField(help_text='Snapshot of item name at report generation', max_length=100)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('closing_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('total_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Inventory Summary',
                'verbose_name_plural': 'Inventory Summaries',
                'ordering': ['inventory_item_id'],
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], help_text='Type of report period', max_length=10)),
                ('start_date', models.DateField(help_text='First day of period')),
                ('end_date', models.DateField(help_text='Last day of period')),
                ('period_label', models.CharField(blank=True, help_text="Human-readable label (e.g., 'December 2025')", max_length=100)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue from sales returns', max_digits=14)),
                ('total_units_sold', models.PositiveIntegerField(default=0, help_text='Total product units sold')),
                ('total_dispatches', models.PositiveIntegerField(default=0, help_text='Number of sales dispatches')),
                ('total_returns', models.PositiveIntegerField(default=0, help_text='Total product units returned unsold')),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commission payments', max_digits=12)),
                ('total_units_produced', models.PositiveIntegerField(default=0, help_text='Total units produced')),
                ('total_batches', models.PositiveIntegerField(default=0, help_text='Number of production batches')),
                ('total_production_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total ingredient cost for production', max_digits=14)),
                ('average_yield_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average yield variance percentage', max_digits=5)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of inventory purchases', max_digits=14)),
                ('total_purchases_count', models.PositiveIntegerField(default=0, help_text='Number of purchase transactions')),
                ('low_stock_alerts', models.PositiveIntegerField(default=0, help_text='Number of low stock alerts')),
                ('total_crates_dispatched', models.PositiveIntegerField(default=0, help_text='Total crates sent out')),
                ('total_crates_returned', models.PositiveIntegerField(default=0, help_text='Total crates returned')),
                ('total_crates_lost', models.PositiveIntegerField(default=0, help_text='Total crates lost')),
                ('total_crates_damaged', models.PositiveIntegerField(default=0, help_text='Total crates damaged')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue - Production Cost', max_digits=14)),
                ('gross_margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(Gross Profit / Revenue) × 100', max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked reports cannot be regenerated')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated list of email recipients')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Period',
                'verbose_name_plural': 'Report Periods',
                'ordering': ['-start_date', 'period_type'],
            },
        ),
        migrations.CreateModel(
            name='ReportProductSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_produced', models.PositiveIntegerField(default=0)),
                ('production_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('batches_count', models.PositiveIntegerField(default=0)),
                ('average_yield_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('units_dispatched', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('units_returned', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_summaries', to='products.product')),
                ('report_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_summaries', to='reports.reportperiod')),
            ],
            options={
                'verbose_name': 'Product Summary',
                'verbose_name_plural': 'Product Summaries',
                'ordering': ['product__name'],
                'unique_together': {('report_period', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ReportSalespersonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_count', models.PositiveIntegerField(default=0)),
                ('total_units_dispatched', models.PositiveIntegerField(default=0)),
                ('total_units_sold', models.PositiveIntegerField(default=0)),
                ('total_units_returned', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('crates_dispatched', models.PositiveIntegerField(default=0)),
                ('crates_returned', models.PositiveIntegerField(default=0)),
                ('crates_lost', models.PositiveIntegerField(default=0)),
                ('crates_damaged', models.PositiveIntegerField(default=0)),
                ('report_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_summaries', to='reports.reportperiod')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salesperson Summary',
                'verbose_name_plural': 'Salesperson Summaries',
                'ordering': ['-total_revenue'],
                'unique_together': {('report_period', 'salesperson')},
            },
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='generated_by',
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.DeleteModel(
            name='WeeklyReport',
        ),
        migrations.AddField(
            model_name='reportinventorysummary',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_summaries', to='reports.reportperiod'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='report_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='reports.reportperiod'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportperiod',
            index=models.Index(fields=['period_type', 'start_date'], name='reports_rep_period__939a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_0980e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportperiod',
            unique_together={('period_type', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='reportinventorysummary',
            unique_together={('report_period', 'inventory_item_id')},
        ),
    ]
