# Generated by Django 5.2.7 on 2025-12-11 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rebuild_reports_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('code', models.CharField(help_text="Unique identifier (e.g., 'pnl_daily', 'sales_summary')", max_length=50, unique=True)),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial Reports'), ('SALES', 'Sales Reports'), ('INVENTORY', 'Inventory Reports'), ('PRODUCTION', 'Production Reports'), ('PAYROLL', 'Payroll Reports')], help_text='Report category', max_length=20)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily (yesterday/today)'), ('WEEKLY', 'Weekly (added on Mondays)'), ('MONTHLY', 'Monthly (added on 1st)'), ('ANNUAL', 'Annual (added Jan 1st)'), ('SNAPSHOT', 'Current snapshot (always included)')], help_text='When this report type applies', max_length=20)),
                ('pdf_view_name', models.CharField(help_text="URL name for PDF view (e.g., 'reports:pnl_daily_pdf')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this report contains')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order within the email (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this report type is available')),
            ],
            options={
                'verbose_name': 'Report Type',
                'verbose_name_plural': 'Report Types',
                'db_table': 'report_type',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this schedule', max_length=100)),
                ('schedule_type', models.CharField(choices=[('MORNING', 'Morning Report (6 AM)'), ('EVENING', 'Evening Report (10 PM)')], help_text='Morning or Evening schedule', max_length=20, unique=True)),
                ('hour', models.PositiveIntegerField(default=6, help_text='Hour to send (0-23, in Africa/Nairobi timezone)', validators=[django.core.validators.MinValueValidator(0)])),
                ('minute', models.PositiveIntegerField(default=0, help_text='Minute to send (0-59)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('subject_template', models.CharField(default='Chesanto Bakery - {schedule_name} - {date}', help_text='Email subject. Use {schedule_name}, {date}, {day_of_week}', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedule',
                'ordering': ['hour', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Recipient name', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to send reports to this recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Link to user account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('schedules', models.ManyToManyField(blank=True, help_text='Which schedules this recipient receives', related_name='recipients', to='reports.reportschedule')),
            ],
            options={
                'verbose_name': 'Report Recipient',
                'verbose_name_plural': 'Report Recipients',
                'db_table': 'report_recipient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating PDFs'), ('SENDING', 'Sending Email'), ('SENT', 'Sent Successfully'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('recipients_list', models.TextField(blank=True, help_text='Comma-separated list of recipient emails')),
                ('reports_included', models.TextField(blank=True, help_text='Comma-separated list of report codes')),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='reports.reportschedule')),
            ],
            options={
                'verbose_name': 'Scheduled Report Log',
                'verbose_name_plural': 'Scheduled Report Logs',
                'db_table': 'scheduled_report_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Order in this schedule's email")),
                ('is_active', models.BooleanField(default=True, help_text='Include in this schedule')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='reports.reporttype')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_reports', to='reports.reportschedule')),
            ],
            options={
                'verbose_name': 'Schedule Report Assignment',
                'verbose_name_plural': 'Schedule Report Assignments',
                'db_table': 'schedule_report',
                'ordering': ['sort_order'],
                'unique_together': {('schedule', 'report_type')},
            },
        ),
    ]
