# Generated by Django 5.2.7 on 2025-12-13 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reporttype_reportschedule_reportrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='day_of_month',
            field=models.PositiveIntegerField(blank=True, help_text='Day of month for MONTHLY/ANNUAL schedules (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='Day of week for WEEKLY schedules (e.g., MON)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='month',
            field=models.PositiveIntegerField(blank=True, help_text='Month for ANNUAL schedules (1=January, 12=December)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='schedule_type',
            field=models.CharField(choices=[('MORNING', 'Morning Report (Daily)'), ('EVENING', 'Evening Report (Daily)'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('ANNUAL', 'Annual Report')], help_text='Schedule frequency type', max_length=20, unique=True),
        ),
    ]
