# Generated by Django 5.2.7 on 2025-12-21 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_periodic_schedule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='hour',
            field=models.PositiveIntegerField(default=21, help_text='Hour to send (0-23, in Africa/Nairobi timezone)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='schedule_type',
            field=models.CharField(choices=[('DAILY', 'Daily Report (9 PM)'), ('WEEKLY', 'Weekly Report (Sunday)'), ('MONTHLY', 'Monthly Report (End of Month)'), ('ANNUAL', 'Annual Report (Dec 31)')], help_text='Schedule frequency type', max_length=20, unique=True),
        ),
    ]
