# Generated by Django 5.2.7 on 2025-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_add_user_link_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employer_remits_nhif',
            field=models.BooleanField(default=True, help_text='If True, employer remits NHIF. If False, employee handles it.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer_remits_nssf',
            field=models.BooleanField(default=True, help_text='If True, employer remits NSSF. If False, employee handles it.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer_remits_paye',
            field=models.BooleanField(default=True, help_text='If True, employer remits PAYE to KRA. If False, employee handles it.'),
        ),
    ]
