# Generated by Django 4.2.23 on 2025-12-06 03:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0003_add_remittance_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Bank Charges', 'License Fees')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this category covers')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive categories won't appear in expense forms")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Misc Expense Category',
                'verbose_name_plural': 'Misc Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MiscExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(help_text='Auto-generated: EXP-YYYYMMDD-XXX', max_length=50, unique=True)),
                ('description', models.CharField(help_text='Brief description of the expense', max_length=500)),
                ('expense_date', models.DateField(help_text='Date expense was incurred')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount (KES)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_number', models.CharField(blank=True, help_text='Receipt/Invoice number (optional)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('category', models.ForeignKey(help_text='Expense category', on_delete=django.db.models.deletion.PROTECT, related_name='expense_records', to='payroll.miscexpensecategory')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this expense', on_delete=django.db.models.deletion.PROTECT, related_name='misc_expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Misc Expense Record',
                'verbose_name_plural': 'Misc Expense Records',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='payroll_mis_expense_b9d308_idx'), models.Index(fields=['category'], name='payroll_mis_categor_b64cc3_idx')],
            },
        ),
    ]
